version: '3.1'

services:
  mysql-ser:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-vol:/var/lib/mysql

  redis-ser:
    image: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis-vol:/data

volumes:
  mysql-vol:
  redis-vol: